### PR TITLE
Add Nuvoton NU_M2354 platform

### PR DESCRIPTION
**Pull request by cyliangtw**
### Description

Add Nuvoton NUMAKER_M2354 target board support . 
According to M2351 experience, target name (platform name + suffix) cannot exceed 20 chars. 
So based on platform name “NUMAKER_M2354”, it will encounter the target name
“NUMAKER_M2354_NPSA_NS” over 20 chars.

Thus, short the platform name as “NU_M2354”.

### Pull request type

    [ ] Fix
    [ ] Refactor
    [x] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### Reviewers

@Ronny-Liu

### CODE REVIEW

**Comment by Ronny-Liu** [comment]
target NU_M2354_NPSA_NS was set up in database.

**Comment by cyliangtw** [comment]
Is there any concern on this PR ?

**Comment by madchutney** [comment]
@MarceloSalazar It appears that this board is listed as `NU_M2354_NPSA_NS` in the online database, should this be corrected?

**Comment by MarceloSalazar** [comment]
It's been corrected. Should be fine now.

**Pull request merged**
