### PR TITLE
Add and updated cypress kits in the platform database

### PR DESCRIPTION
**Pull request by cy-midd**
### Description

Add Cypress PSoC6 kits to the platform database. The Board IDs are as assigned by @maclobdell
Added and updated the following kits,
CYW9P62S1_43012EVB_01: 1903 (Updated)
CY8CKIT_062S2_4343W: 1905 (Updated)
CY8CPROTO_064_SB: 1907 (Added)
CYW9P62S1_43438EVB_01: 1908 (Added)
CY8CKIT_062S2_43012: 190B (Added)
CY8CPROTO-062S3-4343W: 190E (Added)

The corresponding change to mbed-os targets is ongoing.

### Pull request type

    [ ] Fix
    [ ] Refactor
    [x ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### Reviewers
@maclobdell @vmedcy

### CODE REVIEW

**Comment by maclobdell** [comment]
@cy-midd  - Can you please confirm the correct value for the board with ID '190E'

I received notification from Vita that, "CY8CPROTO-062S2-4343W should be renamed to CY8CPROTO-062S3-43012."  Please confirm if that is still correct.  You may need to update your PR.  

@ARMmbed/mbed-os-tools  - Please review and approve once the above entry is confirmed.

**Comment by cy-midd** [comment]
@maclobdell I double checked the kits and I can confirm the for **190E** the kit is **CY8CPROTO-062S3-4343W**. The current data in the pull request is **correct**. Apologies for the confusion, I believe the internal ARM database also have to be updated since the initial value that was submitted was CY8CPROTO-062S3-43012 which was incorrect.

**Comment by maclobdell** [comment]
@ARMmbed/mbed-os-tools  - this should be ready to go.  Please review.

**Comment by maclobdell** [comment]
@madchutney  - are you planning to merge this request and do a release?

**Comment by madchutney** [comment]
@maclobdell This should go out with the next OS patch release.

**Comment by maclobdell** [comment]
@madchutney  - thanks a lot.  Just to clarify, you plan to merge this PR, then make a release, which will be added to the requirements.txt in mbed-os for release 5.13.3?  this will be ready in time for code freeze this week, right?

**Comment by madchutney** [comment]
@maclobdell I've run into a problem, the online database doesn't match the values being submitted here. Can you update the database please?

**Comment by maclobdell** [comment]
@madchutney  - sorry about that, I normally do not bother updating the database to add the target names for pre-released boards.  I have done that now.  

However, I just discovered two problems.  @cy-midd - Can you help resolve these issues?

First - this value in this PR is using dashes (-) instead of underscores.   We recommend underscores (_). 

```
'190E': u'CY8CPROTO-062S3-4343W',
```

Second - several target names are 21 characters long.  However, our system will only accept target names of 20 character or less.

Can you reduce the number of characters by 1 or more?  

```
u'1903': u'CYW9P62S1_43012EVB_01',
u'1908': u'CYW9P62S1_43438EVB_01',
u'1909': u'CY8CPROTO_062S2_43012',
u'190E': u'CY8CPROTO-062S3-4343W',
```

Keep in mind that these values will need to match the target name in mbed-os/targets/targets.json when a pull request is made to add these targets to Mbed OS.

**Comment by mark-edgeworth** [comment]
Unable to pass the last couple of tests because of issues with posting to Coveralls. I'll keep trying, but this is out of our control at the moment.

**Comment by cy-midd** [comment]
@maclobdell I updated the "-" to "_" that was an error. As for the target name length, we are trying to get feedback internally from our marketing team to find the best way to resolve this issue.

**Pull request merged**
