### PR TITLE
Add DISCO_H747I ST board

### PR DESCRIPTION
**Pull request by jeromecoutant**
### Description

Add DISCO_H747I ST board

### Pull request type

    [ ] Fix
    [ ] Refactor
    [x] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### CODE REVIEW

**Comment by jeromecoutant** [comment]
Hi
Any issue for this one ?

**Comment by jeromecoutant** [comment]
As this PR didn't move, I added another H7 board: NUCLEO_H743ZI2

Thx

**Comment by MarceloSalazar** [comment]
@ARMmbed/mbed-os-maintainers please review

**Comment by adbridge** [comment]
@mark-edgeworth @madchutney one of you guys should probably give final approval and merge this

**Comment by MarceloSalazar** [comment]
Thanks!

**Pull request merged**
