### PR TITLE
add NUCLEO_G031K8

### PR DESCRIPTION
**Pull request by pilotak**
### Description

As per https://github.com/ARMmbed/mbed-os/pull/13006 NUCLEO_G031K8 is on the way to the OS
### Pull request type

    [ ] Fix
    [ ] Refactor
    [x] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### Reviewers
@jeromecoutant

### CODE REVIEW

**Comment by pilotak** [comment]
i can see that python 3.7 fails but this is not related to this PR

**Comment by jeromecoutant** [comment]
Any uupdate ?
Thx

**Comment by pilotak** [comment]
@jeromecoutant i believe nothing on my side is blocking this to be merged

**Comment by jeromecoutant** [comment]
When does this PR plan to be in some release version ?

**Pull request merged**
