### PR TITLE
Fix v0.0.7 installation failure with pip.

### PR DESCRIPTION
**Pull request by korjaa**
### Description
Moved test requirements back to setup.py.

Proposed fix for https://github.com/ARMmbed/mbed-os-tools/issues/167

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### CODE REVIEW

**Comment by 0xc0170** [comment]
@madchutney @mark-edgeworth Please review, This issue is blocking many CIs at the moment.

**Comment by 0xc0170** [comment]
One question - how 0.0.7 was tested if it fails to be installed via pip? Do we not test installing at least locally prior releasing ?

**Comment by 0xc0170** [comment]
Approved but looking at #164 - it moved to txt for a reason? This one reverts it partly.

**Comment by korjaa** [comment]
I've got no expertise with this project, but most likely there was a reason to move it out.

**Comment by 0xc0170** [comment]
Note, the tools team is currently in US time zone, we might wait few more hours for review.

**Comment by bridadan** [comment]
Ah actually, this takes a CI tweak as well, I'll follow up with another PR.

**Pull request closed without merging**
